### ISSUE TITLE
Fetch Community from Logged In User

### ISSUE THREAD

**Issue by Dinesh846** [hserv/coordinated-entry#18] opened 2016-05-20 22:35 UTC
Fetch community from logged in user and pass that to survey and inventory micro services to get response for a particular community.

**Comment by eric-jahn** [comment] 2016-05-22 17:57
Waiting on Issue #137 in HMISLynk for this to be resolveable: https://github.com/servinglynk/hmis-lynk-open-source-docs/issues/137

**Comment by eric-jahn** [comment] 2016-05-22 20:51
Duplicate of#10

**Closed by eric-jahn** 2016-05-22 20:51 UTC
Labels: housing_matcher, waiting on HMISLynk functionality
