### ISSUE TITLE
single question within 2 groups

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#175] opened 2018-01-10 16:03 UTC
(filed by @pgorecki)
I'm getting a single question from 2 groups: `fb0fbe41-8fd1-4615-937f-ce7ec22a98d4` and `6666aaf3-33ec-42c1-8b50-c50891568fd7`:
```I20180110-13:42:38.054(1)? debug: HMIS API:get#11 res (https://www.hmislynk.com/survey-api/rest/v2/questiongroups/fb0fbe41-8fd1-4615-937f-ce7ec22a98d4/questions?startIndex=0&maxItems=1) 200
I20180110-13:42:38.055(1)? { from: 0, returned: 1, total: 648, maximum: 30, sort: {} } [ { questionId: 'db7f6f97-5584-4508-a647-5ebc6646f77d',
I20180110-13:42:38.055(1)?     questionDescription: 'Age',
I20180110-13:42:38.055(1)?     displayText: 'Age',
I20180110-13:42:38.055(1)?     questionDataType: 'STRING',
I20180110-13:42:38.055(1)?     questionType: 'TEXT',
I20180110-13:42:38.056(1)?     copyQuestionId: false,
I20180110-13:42:38.056(1)?     hudQuestion: false,
I20180110-13:42:38.056(1)?     locked: false,
I20180110-13:42:38.056(1)?     questionWeight: 0,
I20180110-13:42:38.056(1)?     questionGroupId: '95bdca23-5135-4552-9f11-819cab1aaa45',
I20180110-13:42:38.056(1)?     visibility: true } ]

I20180110-13:42:38.830(1)? debug: HMIS API:get#12 res (https://www.hmislynk.com/survey-api/rest/v2/questiongroups/6666aaf3-33ec-42c1-8b50-c50891568fd7/questions?startIndex=0&maxItems=1) 200
I20180110-13:42:38.831(1)? { from: 0, returned: 1, total: 648, maximum: 30, sort: {} } [ { questionId: 'db7f6f97-5584-4508-a647-5ebc6646f77d',
I20180110-13:42:38.831(1)?     questionDescription: 'Age',
I20180110-13:42:38.831(1)?     displayText: 'Age',
I20180110-13:42:38.831(1)?     questionDataType: 'STRING',
I20180110-13:42:38.831(1)?     questionType: 'TEXT',
I20180110-13:42:38.831(1)?     copyQuestionId: false,
I20180110-13:42:38.832(1)?     hudQuestion: false,
I20180110-13:42:38.832(1)?     locked: false,
I20180110-13:42:38.832(1)?     questionWeight: 0,
I20180110-13:42:38.832(1)?     questionGroupId: '95bdca23-5135-4552-9f11-819cab1aaa45',
I20180110-13:42:38.832(1)?     visibility: true } ]
```

In both cases I'm getting a question with questionGroupId `95bdca23-5135-4552-9f11-819cab1aaa45`

**Comment by suryayadavalli** [comment] 2018-01-10 18:28
@pgorecki : will look into this and get back to you shortly

**Comment by suryabi** [comment] 2018-01-11 05:45
@pgorecki : I see that in the GET request URL that you posted above , the request is GETonly 1 question (Check the request parameter "**maxItems**" value ).  maxItems is the number of items that you would like the cloud to send in the response. Can you double check from your end and let me know. 

https://www.hmislynk.com/survey-api/rest/v2/questiongroups/6666aaf3-33ec-42c1-8b50-c50891568fd7/questions?startIndex=0&**maxItems=1**

As you can see in the response - You can see that number of items returned is 1 while the total available are 648.  
{ from: 0, returned: 1, total: 648, maximum: 30, sort: {} }

**Comment by pgorecki** [comment] 2018-01-11 18:57
There is a problem with the issue description, 1st line with 1st get request url is missing.
The problem is not about getting a single question, I'm setting maxItems on purpose. 

The real problem is that for the following requests the response is the same. Regardless of the questionGroupId in the url, the response is the same question for a  froupId: '95bdca23-5135-4552-9f11-819cab1aaa45', which is wrong since I didn't ask for group 95bdca23-5135-4552-9f11-819cab1aaa45 but for groupus fb0fbe41-8fd1-4615-937f-ce7ec22a98d4 and 6666aaf3-33ec-42c1-8b50-c50891568fd7.

https://www.hmislynk.com/survey-api/rest/v2/questiongroups/fb0fbe41-8fd1-4615-937f-ce7ec22a98d4/questions?startIndex=0&maxItems=1

https://www.hmislynk.com/survey-api/rest/v2/questiongroups/6666aaf3-33ec-42c1-8b50-c50891568fd7/questions?startIndex=0&maxItems=1

both give the same response:
```
{ questionId: 'db7f6f97-5584-4508-a647-5ebc6646f77d',
I20180110-13:42:38.831(1)?     questionDescription: 'Age',
I20180110-13:42:38.831(1)?     displayText: 'Age',
I20180110-13:42:38.831(1)?     questionDataType: 'STRING',
I20180110-13:42:38.831(1)?     questionType: 'TEXT',
I20180110-13:42:38.831(1)?     copyQuestionId: false,
I20180110-13:42:38.832(1)?     hudQuestion: false,
I20180110-13:42:38.832(1)?     locked: false,
I20180110-13:42:38.832(1)?     questionWeight: 0,
I20180110-13:42:38.832(1)?     questionGroupId: '95bdca23-5135-4552-9f11-819cab1aaa45',
I20180110-13:42:38.832(1)?     visibility: true 
```

**Comment by suryabi** [comment] 2018-01-11 20:02
@pgorecki : I believe you meant *same* question in the response , not *single* question.  Will take a look at this.

**Comment by suryayadavalli** [comment] 2018-01-12 19:19
@pgorecki : this is a prod issue on our end and has been fixed now. Can you please verify and update the ticket with the status. Thanks !

**Comment by pgorecki** [comment] 2018-01-18 17:33
It works as expected now.

pt., 12.01.2018, 20:50 użytkownik suryayadavalli <notifications@github.com>
napisał:

**Comment by eric-jahn** [comment] 2018-01-18 18:04
thanks for verifying @pgorecki

**Closed** 2018-01-18 18:03 UTC
Labels: bug, current sprint, survey_service, top priority
