### ISSUE TITLE
questions created by one project group are accessible in another

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#148] opened 2017-12-13 21:23 UTC
cc: @CTAJavier

**Comment by eric-jahn** [comment] 2017-12-13 21:24
@CTAJavier has already provided @suryayadavalli question IDs for the problem

**Comment by suryabi** [comment] 2017-12-13 22:34
@CTAJavier :  Can you please verify this issue from your end and confirm if this is resolved.

**Comment by CTAJavier** [comment] 2017-12-13 22:38
Still occurring, the Issue is when posting response

**Comment by suryayadavalli** [comment] 2017-12-13 23:20
@CTAJavier : please find the following details.

For the survey in question **Youth VI SPDAT**  (belongs to **Monterey** project group), we have the following questions associated that **DO NOT** belong to Monterey project group. 

The reason that these questions are mapped to HOME is due the fact that the question group is created by user belongs to HOME (udit). If you can confirm that these questions should belong to MONTEREY, we will update these records at our end.

Question | Project Group | Question Group
-- | -- | --
VI NOTES | HO0002 | 95bdca23-5135-4552-9f11-819cab1aaa45
Where do   you sleep most frequently? | HO0002 | 95bdca23-5135-4552-9f11-819cab1aaa45
12. Do   you get any money from the government, an inheritance, an allowance, working   under the table, a regular job, or anything like that? TAY | HO0002 | 95bdca23-5135-4552-9f11-819cab1aaa45
Is there   a phone number and/or email where someone can safely get in touch with you or   leave you a message? | HO0002 | 95bdca23-5135-4552-9f11-819cab1aaa45
15. Is   your current lack of stable housing ... TAY | HO0002 | 95bdca23-5135-4552-9f11-819cab1aaa45
4. In   the past six months, how many times have you ... | HO0002 | 95bdca23-5135-4552-9f11-819cab1aaa45
13. Do   you have planned activities, other than just surviving, that make you fell   happy and fulfilled? TAY | HO0002 | 95bdca23-5135-4552-9f11-819cab1aaa45
17. Do   you have any chronic health issues with your liver, kidneys, stomach, lungs   or heart? TAY | HO0002 | 95bdca23-5135-4552-9f11-819cab1aaa45
23. Will   drinking or drugs use make it difficult for you to stay housed or afford your   housing? TAY | HO0002 | 95bdca23-5135-4552-9f11-819cab1aaa45
19. Do   you have any physical disabilities that would limit the type of housing you   could access, or would make it hard to live independently because you'd need   help? TAY | HO0002 | 95bdca23-5135-4552-9f11-819cab1aaa45

**Comment by CTAJavier** [comment] 2017-12-13 23:56
Any questions created by Udit should belong to Monterey Project Group. Thanks

**Comment by CTAJavier** [comment] 2017-12-14 00:54
Fixed Thanks guys

*Javier Celedon*
*Operations Director*
Direct: (408) 437-9168
Main: (408) 437-8800
*Facebook <http://www.facebook.com/ctagroup.org> • Twitter
<https://twitter.com/CTA_Group_> • Video
<http://www.ctagroup.org/what-we-do/video/>*

<http://www.ctagroup.org/>

**Comment by suryayadavalli** [comment] 2017-12-18 19:25
Closing this issue. Resolved and Verified

**Closed by suryayadavalli** 2017-12-18 19:25 UTC
Labels: bug, current sprint, top priority
