### ISSUE TITLE
Rule engine to handle rules related each community via XML or similar.

### ISSUE THREAD

**Issue by logicsandeep** [hserv/coordinated-entry#13] opened 2016-05-20 15:08 UTC

**Comment by eric-jahn** [comment] 2016-05-20 15:34
This may be something HMISLynk handles for any app. See https://github.com/servinglynk/hmis-lynk-open-source-docs/issues/136 .

**Comment by eric-jahn** [comment] 2016-10-19 15:17
duplicate of Issue #40 40

**Closed by eric-jahn** 2016-10-19 15:17 UTC
Labels: duplicate, housing_matcher
